// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHVZJW8yhowAcoCPPZTUje4LlxmEdsZgY',
    appId: '1:970559476071:web:b1843a5838730ac6481fc2',
    messagingSenderId: '970559476071',
    projectId: 'socialapp-d525b',
    authDomain: 'socialapp-d525b.firebaseapp.com',
    storageBucket: 'socialapp-d525b.firebasestorage.app',
    measurementId: 'G-B2LKCNND18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEBUOA9588kCBvNg3VxAi7Vw9o4XlIdNs',
    appId: '1:970559476071:android:4a2462f501ae00c6481fc2',
    messagingSenderId: '970559476071',
    projectId: 'socialapp-d525b',
    storageBucket: 'socialapp-d525b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rWEc2kcWyFiO9SL8h3xVyzYQnVtT-BQ',
    appId: '1:970559476071:ios:a5f32a1ef9633e84481fc2',
    messagingSenderId: '970559476071',
    projectId: 'socialapp-d525b',
    storageBucket: 'socialapp-d525b.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );
}
